-------------
terminal = "lxterminal"
manager = "dolphin"
editor = "vim"
editor_cmd = terminal .. " -e " .. editor
apparence = "lxappearance"
archiver = "file-roller"
guieditor = "gvim"
filer = "dolphin"
mediaplayer = "vlc"
musicplayer = terminal .. " -e ncmpcpp"
--irc = terminal .. "-T weechat -e weechat-curses"
irc = "xchat"
burner = "brasero"
webcli = "dwb"
webgui = "iceweasel"
ftpgui = "filezilla"
torrent = "deluge"
writer = "lowriter"
tableur = "localc"
calc = "kcalc"
pdf = "okular"
imageviewer = "eog"
locker = "slock"
-----------------------------------------
